_wandb:
    value:
        cli_version: 0.18.1
        code_path: code/train_custom_augmentation.py
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 41
                - 55
                - 80
            "3":
                - 23
                - 55
            "4": 3.8.20
            "5": 0.18.1
            "8":
                - 3
                - 5
            "12": 0.18.1
            "13": windows-amd64
