_wandb:
    value:
        cli_version: 0.18.1
        code_path: code/train_custom_augmentation.py
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 41
                - 55
                - 80
            "2":
                - 1
                - 41
                - 55
                - 80
            "3":
                - 17
                - 19
                - 23
                - 55
            "4": 3.8.20
            "5": 0.18.1
            "8":
                - 3
                - 5
            "10":
                - 3
            "12": 0.18.1
            "13": windows-amd64
batch_size:
    value: 10
computer:
    value: ws2080
conf_thres:
    value: 0.1
configuration:
    value: 0
early_stopping_patience:
    value: 25
lr:
    value: 0.005
nms_thres:
    value: 0.2
num_epochs:
    value: 300
num_gpus:
    value: 2
num_worker:
    value: 8
project_name:
    value: fold_0
